name: Lint

on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  lint-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 22 and pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint

      - name: Check Prettier formatting
        run: pnpm run prettier
